development:
  adapter:  postgresql
  database: rtchallenge
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host:     localhost
production:
  adapter:  postgresql
  database: rtchallenge
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host:     localhost
